baseURL = "http://example.org/"
languageCode = "en-us"
title = "Charliemcr"
theme = "charliemcr"
MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/charliemcr"
  instagram = ""
  youtube = ""
  github = "https://github.com/CharlieMCR"
  linkedin = "https://www.linkedin.com/in/charlie-heesom-7b89a3101/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-primary"
  featured_image = "/images/bg-hd.jpg"
#[params]
#	twitter = "charliemcr"
#	github = "charliemcr"
#	stackoverflow = "4244751/charliemcr"